/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.erDsl2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.erDsl2.Attribute#isIsKey <em>Is Key</em>}</li>
 *   <li>{@link org.xtext.example.erDsl2.Attribute#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.erDsl2.Attribute#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.erDsl2.ErDsl2Package#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Key</em>' attribute.
   * @see #setIsKey(boolean)
   * @see org.xtext.example.erDsl2.ErDsl2Package#getAttribute_IsKey()
   * @model
   * @generated
   */
  boolean isIsKey();

  /**
   * Sets the value of the '{@link org.xtext.example.erDsl2.Attribute#isIsKey <em>Is Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Key</em>' attribute.
   * @see #isIsKey()
   * @generated
   */
  void setIsKey(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.erDsl2.ErDsl2Package#getAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.erDsl2.Attribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.erDsl2.DataType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.erDsl2.DataType
   * @see #setType(DataType)
   * @see org.xtext.example.erDsl2.ErDsl2Package#getAttribute_Type()
   * @model
   * @generated
   */
  DataType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.erDsl2.Attribute#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.erDsl2.DataType
   * @see #getType()
   * @generated
   */
  void setType(DataType value);

} // Attribute
