/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.erDsl2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.erDsl2.Relation#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.erDsl2.Relation#getLeftEnding <em>Left Ending</em>}</li>
 *   <li>{@link org.xtext.example.erDsl2.Relation#getRightEnding <em>Right Ending</em>}</li>
 *   <li>{@link org.xtext.example.erDsl2.Relation#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.erDsl2.ErDsl2Package#getRelation()
 * @model
 * @generated
 */
public interface Relation extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.erDsl2.ErDsl2Package#getRelation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.erDsl2.Relation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Left Ending</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Ending</em>' containment reference.
   * @see #setLeftEnding(RelationSide)
   * @see org.xtext.example.erDsl2.ErDsl2Package#getRelation_LeftEnding()
   * @model containment="true"
   * @generated
   */
  RelationSide getLeftEnding();

  /**
   * Sets the value of the '{@link org.xtext.example.erDsl2.Relation#getLeftEnding <em>Left Ending</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Ending</em>' containment reference.
   * @see #getLeftEnding()
   * @generated
   */
  void setLeftEnding(RelationSide value);

  /**
   * Returns the value of the '<em><b>Right Ending</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Ending</em>' containment reference.
   * @see #setRightEnding(RelationSide)
   * @see org.xtext.example.erDsl2.ErDsl2Package#getRelation_RightEnding()
   * @model containment="true"
   * @generated
   */
  RelationSide getRightEnding();

  /**
   * Sets the value of the '{@link org.xtext.example.erDsl2.Relation#getRightEnding <em>Right Ending</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right Ending</em>' containment reference.
   * @see #getRightEnding()
   * @generated
   */
  void setRightEnding(RelationSide value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.erDsl2.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.xtext.example.erDsl2.ErDsl2Package#getRelation_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // Relation
