/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import versao2.ui.internal.Versao2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ErDsl2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Versao2Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Versao2Activator activator = Versao2Activator.getInstance();
		return activator != null ? activator.getInjector(Versao2Activator.ORG_XTEXT_EXAMPLE_ERDSL2) : null;
	}

}
