/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.ui.contentassist;

import org.xtext.example.ui.contentassist.AbstractErDsl2ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ErDsl2ProposalProvider extends AbstractErDsl2ProposalProvider {
}
