/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.ui.AbstractErDsl2UiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ErDsl2UiModule extends AbstractErDsl2UiModule {
  public ErDsl2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
