/*
 * generated by Xtext 2.25.0
 */
package org.xtext.unipampa.erdsl.ui.wizard;

import org.eclipse.osgi.util.NLS;

public class Messages extends NLS {
	private static final String BUNDLE_NAME = "org.xtext.unipampa.erdsl.ui.wizard.messages"; //$NON-NLS-1$
	
	public static String ERtextFile_Label;
	public static String ERtextFile_Description;
	public static String ERtextProject_Label;
	public static String ERtextProject_Description;
	
	static {
	// initialize resource bundle
	NLS.initializeMessages(BUNDLE_NAME, Messages.class);
	}

	private Messages() {
	}
}
