/**
 * generated by Xtext 2.25.0
 */
package org.xtext.unipampa.erdsl.erDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.unipampa.erdsl.erDsl.ErDslFactory
 * @model kind="package"
 * @generated
 */
public interface ErDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "erDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/unipampa/erdsl/ErDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "erDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ErDslPackage eINSTANCE = org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.ERModelImpl <em>ER Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unipampa.erdsl.erDsl.impl.ERModelImpl
   * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getERModel()
   * @generated
   */
  int ER_MODEL = 0;

  /**
   * The feature id for the '<em><b>Target Generator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ER_MODEL__TARGET_GENERATOR = 0;

  /**
   * The feature id for the '<em><b>Domain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ER_MODEL__DOMAIN = 1;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ER_MODEL__ENTITIES = 2;

  /**
   * The feature id for the '<em><b>Relations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ER_MODEL__RELATIONS = 3;

  /**
   * The number of structural features of the '<em>ER Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ER_MODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.DomainImpl <em>Domain</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unipampa.erdsl.erDsl.impl.DomainImpl
   * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getDomain()
   * @generated
   */
  int DOMAIN = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN__NAME = 0;

  /**
   * The number of structural features of the '<em>Domain</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unipampa.erdsl.erDsl.impl.AttributeImpl
   * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 1;

  /**
   * The feature id for the '<em><b>Is Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__IS_KEY = 2;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unipampa.erdsl.erDsl.impl.EntityImpl
   * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Generalization</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__GENERALIZATION = 1;

  /**
   * The feature id for the '<em><b>Is</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__IS = 2;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__ATTRIBUTES = 3;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.RelationImpl <em>Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unipampa.erdsl.erDsl.impl.RelationImpl
   * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getRelation()
   * @generated
   */
  int RELATION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Left Ending</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__LEFT_ENDING = 1;

  /**
   * The feature id for the '<em><b>Right Ending</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__RIGHT_ENDING = 2;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__ATTRIBUTES = 3;

  /**
   * The number of structural features of the '<em>Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.RelationSideRightImpl <em>Relation Side Right</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unipampa.erdsl.erDsl.impl.RelationSideRightImpl
   * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getRelationSideRight()
   * @generated
   */
  int RELATION_SIDE_RIGHT = 5;

  /**
   * The feature id for the '<em><b>Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SIDE_RIGHT__CARDINALITY = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SIDE_RIGHT__TARGET = 1;

  /**
   * The number of structural features of the '<em>Relation Side Right</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SIDE_RIGHT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.RelationSideLeftImpl <em>Relation Side Left</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unipampa.erdsl.erDsl.impl.RelationSideLeftImpl
   * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getRelationSideLeft()
   * @generated
   */
  int RELATION_SIDE_LEFT = 6;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SIDE_LEFT__TARGET = 0;

  /**
   * The feature id for the '<em><b>Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SIDE_LEFT__CARDINALITY = 1;

  /**
   * The number of structural features of the '<em>Relation Side Left</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_SIDE_LEFT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.unipampa.erdsl.erDsl.DataType <em>Data Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.unipampa.erdsl.erDsl.DataType
   * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 7;


  /**
   * Returns the meta object for class '{@link org.xtext.unipampa.erdsl.erDsl.ERModel <em>ER Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ER Model</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.ERModel
   * @generated
   */
  EClass getERModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unipampa.erdsl.erDsl.ERModel#getTargetGenerator <em>Target Generator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target Generator</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.ERModel#getTargetGenerator()
   * @see #getERModel()
   * @generated
   */
  EAttribute getERModel_TargetGenerator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.unipampa.erdsl.erDsl.ERModel#getDomain <em>Domain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Domain</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.ERModel#getDomain()
   * @see #getERModel()
   * @generated
   */
  EReference getERModel_Domain();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unipampa.erdsl.erDsl.ERModel#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.ERModel#getEntities()
   * @see #getERModel()
   * @generated
   */
  EReference getERModel_Entities();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unipampa.erdsl.erDsl.ERModel#getRelations <em>Relations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Relations</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.ERModel#getRelations()
   * @see #getERModel()
   * @generated
   */
  EReference getERModel_Relations();

  /**
   * Returns the meta object for class '{@link org.xtext.unipampa.erdsl.erDsl.Domain <em>Domain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Domain
   * @generated
   */
  EClass getDomain();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unipampa.erdsl.erDsl.Domain#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Domain#getName()
   * @see #getDomain()
   * @generated
   */
  EAttribute getDomain_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.unipampa.erdsl.erDsl.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unipampa.erdsl.erDsl.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unipampa.erdsl.erDsl.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unipampa.erdsl.erDsl.Attribute#isIsKey <em>Is Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Key</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Attribute#isIsKey()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_IsKey();

  /**
   * Returns the meta object for class '{@link org.xtext.unipampa.erdsl.erDsl.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unipampa.erdsl.erDsl.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unipampa.erdsl.erDsl.Entity#getGeneralization <em>Generalization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Generalization</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Entity#getGeneralization()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Generalization();

  /**
   * Returns the meta object for the reference '{@link org.xtext.unipampa.erdsl.erDsl.Entity#getIs <em>Is</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Is</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Entity#getIs()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Is();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unipampa.erdsl.erDsl.Entity#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Entity#getAttributes()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Attributes();

  /**
   * Returns the meta object for class '{@link org.xtext.unipampa.erdsl.erDsl.Relation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Relation
   * @generated
   */
  EClass getRelation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unipampa.erdsl.erDsl.Relation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Relation#getName()
   * @see #getRelation()
   * @generated
   */
  EAttribute getRelation_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.unipampa.erdsl.erDsl.Relation#getLeftEnding <em>Left Ending</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left Ending</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Relation#getLeftEnding()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_LeftEnding();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.unipampa.erdsl.erDsl.Relation#getRightEnding <em>Right Ending</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Ending</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Relation#getRightEnding()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_RightEnding();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.unipampa.erdsl.erDsl.Relation#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.Relation#getAttributes()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Attributes();

  /**
   * Returns the meta object for class '{@link org.xtext.unipampa.erdsl.erDsl.RelationSideRight <em>Relation Side Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation Side Right</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.RelationSideRight
   * @generated
   */
  EClass getRelationSideRight();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unipampa.erdsl.erDsl.RelationSideRight#getCardinality <em>Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cardinality</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.RelationSideRight#getCardinality()
   * @see #getRelationSideRight()
   * @generated
   */
  EAttribute getRelationSideRight_Cardinality();

  /**
   * Returns the meta object for the reference '{@link org.xtext.unipampa.erdsl.erDsl.RelationSideRight#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.RelationSideRight#getTarget()
   * @see #getRelationSideRight()
   * @generated
   */
  EReference getRelationSideRight_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.unipampa.erdsl.erDsl.RelationSideLeft <em>Relation Side Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation Side Left</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.RelationSideLeft
   * @generated
   */
  EClass getRelationSideLeft();

  /**
   * Returns the meta object for the reference '{@link org.xtext.unipampa.erdsl.erDsl.RelationSideLeft#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.RelationSideLeft#getTarget()
   * @see #getRelationSideLeft()
   * @generated
   */
  EReference getRelationSideLeft_Target();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.unipampa.erdsl.erDsl.RelationSideLeft#getCardinality <em>Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cardinality</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.RelationSideLeft#getCardinality()
   * @see #getRelationSideLeft()
   * @generated
   */
  EAttribute getRelationSideLeft_Cardinality();

  /**
   * Returns the meta object for enum '{@link org.xtext.unipampa.erdsl.erDsl.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Data Type</em>'.
   * @see org.xtext.unipampa.erdsl.erDsl.DataType
   * @generated
   */
  EEnum getDataType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ErDslFactory getErDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.ERModelImpl <em>ER Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unipampa.erdsl.erDsl.impl.ERModelImpl
     * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getERModel()
     * @generated
     */
    EClass ER_MODEL = eINSTANCE.getERModel();

    /**
     * The meta object literal for the '<em><b>Target Generator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ER_MODEL__TARGET_GENERATOR = eINSTANCE.getERModel_TargetGenerator();

    /**
     * The meta object literal for the '<em><b>Domain</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ER_MODEL__DOMAIN = eINSTANCE.getERModel_Domain();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ER_MODEL__ENTITIES = eINSTANCE.getERModel_Entities();

    /**
     * The meta object literal for the '<em><b>Relations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ER_MODEL__RELATIONS = eINSTANCE.getERModel_Relations();

    /**
     * The meta object literal for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.DomainImpl <em>Domain</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unipampa.erdsl.erDsl.impl.DomainImpl
     * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getDomain()
     * @generated
     */
    EClass DOMAIN = eINSTANCE.getDomain();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOMAIN__NAME = eINSTANCE.getDomain_Name();

    /**
     * The meta object literal for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unipampa.erdsl.erDsl.impl.AttributeImpl
     * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '<em><b>Is Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__IS_KEY = eINSTANCE.getAttribute_IsKey();

    /**
     * The meta object literal for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unipampa.erdsl.erDsl.impl.EntityImpl
     * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '<em><b>Generalization</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__GENERALIZATION = eINSTANCE.getEntity_Generalization();

    /**
     * The meta object literal for the '<em><b>Is</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__IS = eINSTANCE.getEntity_Is();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__ATTRIBUTES = eINSTANCE.getEntity_Attributes();

    /**
     * The meta object literal for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.RelationImpl <em>Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unipampa.erdsl.erDsl.impl.RelationImpl
     * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getRelation()
     * @generated
     */
    EClass RELATION = eINSTANCE.getRelation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATION__NAME = eINSTANCE.getRelation_Name();

    /**
     * The meta object literal for the '<em><b>Left Ending</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__LEFT_ENDING = eINSTANCE.getRelation_LeftEnding();

    /**
     * The meta object literal for the '<em><b>Right Ending</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__RIGHT_ENDING = eINSTANCE.getRelation_RightEnding();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__ATTRIBUTES = eINSTANCE.getRelation_Attributes();

    /**
     * The meta object literal for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.RelationSideRightImpl <em>Relation Side Right</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unipampa.erdsl.erDsl.impl.RelationSideRightImpl
     * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getRelationSideRight()
     * @generated
     */
    EClass RELATION_SIDE_RIGHT = eINSTANCE.getRelationSideRight();

    /**
     * The meta object literal for the '<em><b>Cardinality</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATION_SIDE_RIGHT__CARDINALITY = eINSTANCE.getRelationSideRight_Cardinality();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_SIDE_RIGHT__TARGET = eINSTANCE.getRelationSideRight_Target();

    /**
     * The meta object literal for the '{@link org.xtext.unipampa.erdsl.erDsl.impl.RelationSideLeftImpl <em>Relation Side Left</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unipampa.erdsl.erDsl.impl.RelationSideLeftImpl
     * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getRelationSideLeft()
     * @generated
     */
    EClass RELATION_SIDE_LEFT = eINSTANCE.getRelationSideLeft();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_SIDE_LEFT__TARGET = eINSTANCE.getRelationSideLeft_Target();

    /**
     * The meta object literal for the '<em><b>Cardinality</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATION_SIDE_LEFT__CARDINALITY = eINSTANCE.getRelationSideLeft_Cardinality();

    /**
     * The meta object literal for the '{@link org.xtext.unipampa.erdsl.erDsl.DataType <em>Data Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.unipampa.erdsl.erDsl.DataType
     * @see org.xtext.unipampa.erdsl.erDsl.impl.ErDslPackageImpl#getDataType()
     * @generated
     */
    EEnum DATA_TYPE = eINSTANCE.getDataType();

  }

} //ErDslPackage
