/**
 * generated by Xtext 2.25.0
 */
package org.xtext.unipampa.erdsl.erDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation Side Right</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.unipampa.erdsl.erDsl.RelationSideRight#getCardinality <em>Cardinality</em>}</li>
 *   <li>{@link org.xtext.unipampa.erdsl.erDsl.RelationSideRight#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see org.xtext.unipampa.erdsl.erDsl.ErDslPackage#getRelationSideRight()
 * @model
 * @generated
 */
public interface RelationSideRight extends EObject
{
  /**
   * Returns the value of the '<em><b>Cardinality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardinality</em>' attribute.
   * @see #setCardinality(String)
   * @see org.xtext.unipampa.erdsl.erDsl.ErDslPackage#getRelationSideRight_Cardinality()
   * @model
   * @generated
   */
  String getCardinality();

  /**
   * Sets the value of the '{@link org.xtext.unipampa.erdsl.erDsl.RelationSideRight#getCardinality <em>Cardinality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardinality</em>' attribute.
   * @see #getCardinality()
   * @generated
   */
  void setCardinality(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(EObject)
   * @see org.xtext.unipampa.erdsl.erDsl.ErDslPackage#getRelationSideRight_Target()
   * @model
   * @generated
   */
  EObject getTarget();

  /**
   * Sets the value of the '{@link org.xtext.unipampa.erdsl.erDsl.RelationSideRight#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(EObject value);

} // RelationSideRight
