/**
 * generated by Xtext 2.17.0
 */
package org.xtext.unipampa.erdsl;

import org.xtext.unipampa.erdsl.AbstractErDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ErDslRuntimeModule extends AbstractErDslRuntimeModule {
}
