/**
 * generated by Xtext 2.17.0
 */
package org.xtext.unipampa.erdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.unipampa.erdsl.ErDslRuntimeModule;
import org.xtext.unipampa.erdsl.ErDslStandaloneSetup;
import org.xtext.unipampa.erdsl.ide.ErDslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ErDslIdeSetup extends ErDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    ErDslRuntimeModule _erDslRuntimeModule = new ErDslRuntimeModule();
    ErDslIdeModule _erDslIdeModule = new ErDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_erDslRuntimeModule, _erDslIdeModule));
  }
}
