/**
 * generated by Xtext 2.17.0
 */
package org.xtext.unipampa.erdsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ErDslIdeModule extends AbstractErDslIdeModule {
}
