/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.erDsl2.Attribute;
import org.xtext.example.erDsl2.Domain;
import org.xtext.example.erDsl2.ERModel;
import org.xtext.example.erDsl2.Entity;
import org.xtext.example.erDsl2.ErDsl2Package;
import org.xtext.example.erDsl2.Relation;
import org.xtext.example.erDsl2.RelationSide;
import org.xtext.example.services.ErDsl2GrammarAccess;

@SuppressWarnings("all")
public class ErDsl2SemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ErDsl2GrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ErDsl2Package.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ErDsl2Package.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case ErDsl2Package.DOMAIN:
				sequence_Domain(context, (Domain) semanticObject); 
				return; 
			case ErDsl2Package.ER_MODEL:
				sequence_ERModel(context, (ERModel) semanticObject); 
				return; 
			case ErDsl2Package.ENTITY:
				sequence_Entity(context, (Entity) semanticObject); 
				return; 
			case ErDsl2Package.RELATION:
				sequence_Relation(context, (Relation) semanticObject); 
				return; 
			case ErDsl2Package.RELATION_SIDE:
				sequence_RelationSide(context, (RelationSide) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Attribute returns Attribute
	 *
	 * Constraint:
	 *     (isKey?='*'? name=ID type=DataType)
	 */
	protected void sequence_Attribute(ISerializationContext context, Attribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Domain returns Domain
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Domain(ISerializationContext context, Domain semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ErDsl2Package.Literals.DOMAIN__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ErDsl2Package.Literals.DOMAIN__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDomainAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ERModel returns ERModel
	 *
	 * Constraint:
	 *     (domain=Domain entities+=Entity+ relations+=Relation*)
	 */
	protected void sequence_ERModel(ISerializationContext context, ERModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Entity returns Entity
	 *
	 * Constraint:
	 *     (name=ID isA+=[Entity|ID]* (attributes+=Attribute attributes+=Attribute*)?)
	 */
	protected void sequence_Entity(ISerializationContext context, Entity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     RelationSide returns RelationSide
	 *
	 * Constraint:
	 *     (((Cardinality='(0,1)' | Cardinality='(1,1)' | Cardinality='(0,N)' | Cardinality='(1,N)') target=[Entity|ID]) | target=[Relation|ID])
	 */
	protected void sequence_RelationSide(ISerializationContext context, RelationSide semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Relation returns Relation
	 *
	 * Constraint:
	 *     (name=ID? leftEnding=RelationSide rightEnding=RelationSide (attributes+=Attribute attributes+=Attribute*)*)
	 */
	protected void sequence_Relation(ISerializationContext context, Relation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
