/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.ErDsl2RuntimeModule
import org.xtext.example.ErDsl2StandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ErDsl2IdeSetup extends ErDsl2StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ErDsl2RuntimeModule, new ErDsl2IdeModule))
	}
	
}
