/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ErDsl2StandaloneSetup extends ErDsl2StandaloneSetupGenerated {

	def static void doSetup() {
		new ErDsl2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
