/*
 * generated by Xtext 2.17.1
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.parser.antlr.internal.InternalErDsl2Parser;
import org.xtext.example.services.ErDsl2GrammarAccess;

public class ErDsl2Parser extends AbstractAntlrParser {

	@Inject
	private ErDsl2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalErDsl2Parser createParser(XtextTokenStream stream) {
		return new InternalErDsl2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ERModel";
	}

	public ErDsl2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ErDsl2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
