/**
 * generated by Xtext 2.17.0
 */
package org.xtext.unipampa.erdsl.scoping;

import com.google.common.base.Objects;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.xtext.unipampa.erdsl.erDsl.ERModel;
import org.xtext.unipampa.erdsl.erDsl.Entity;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ErDslScopeProvider extends AbstractErDslScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    if ((context instanceof Entity)) {
      EObject _eContainer = ((Entity)context).eContainer();
      final Function1<Entity, Boolean> _function = (Entity x) -> {
        return Boolean.valueOf((!Objects.equal(x, context)));
      };
      return Scopes.scopeFor(
        IterableExtensions.<Entity>filter(((ERModel) _eContainer).getEntities(), _function));
    }
    return super.getScope(context, reference);
  }
}
