/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.ide;

import org.xtext.example.ide.AbstractErDsl2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ErDsl2IdeModule extends AbstractErDsl2IdeModule {
}
