/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example;

import org.xtext.example.AbstractErDsl2RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ErDsl2RuntimeModule extends AbstractErDsl2RuntimeModule {
}
