/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.validation;

import org.xtext.example.validation.AbstractErDsl2Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ErDsl2Validator extends AbstractErDsl2Validator {
}
